= SoapUI Runner Gradle Plugin image:https://travis-ci.org/daggerok/soapui-runner.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/soapui-runner"]
author: Maksim Kostromin
:toc:

This repository contains simple gradle plugin (written in groovy) allowed configure and run SoapUI tests using gradle. link:https://github.com/daggerok/soapui-testrunner-groovy-example[see usage example]

== usage

=== three plugins available on Gradle Portal

. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-testrunner[SoapUI Test Runner Plugin] soapui-testrunner (`io.github.daggerok.soapui-testrunner`)
. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-loadtestrunner[SoapUI Load Test Runner Plugin] soapui-loadtestrunner (`io.github.daggerok.soapui-loadtestrunner`)
. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-runner[SoapUI Runner Plugin] soapui-runner (`io.github.daggerok.soapui-runner`) - contains all tasks: testrunner and loadtestrunner

==== using plugins (gradle >= 2.1)

[source,gradle]
----
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'http://smartbearsoftware.com/repository/maven2/' }
  }
}

plugins {
  id 'io.github.daggerok.soapui-runner' version '5.3.0'
}
----

==== using apply plugin (old way)

[source,gradle]
----
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'http://smartbearsoftware.com/repository/maven2/' }
  }
  dependencies {
    classpath 'gradle.plugin.io.github.daggerok:soapui-runner:5.3.0'
  }
}

apply plugin: 'io.github.daggerok.soapui-runner'
----

==== runners configuration

[source,gradle]
----
testrunner {
  projectFile 'src/test/resources/soapui-test-project.xml'
  outputFolder 'out/tests'
  failOnError true

  projectProperties = [
    'apiBaseUrl=https://api.github.com'
  ]
}

loadtestrunner {
  projectFile = "$projectDir/soapui-load-tests.xml"
  outputFolder = "buildDir/soapui/load"
}
----

testrunner and loadtestrunner tasks or theirs configurations could be omitted if default properties are good enough for you ([see configuration](https://github.com/daggerok/soapui-runner/tree/master#configurations):

[source,gradle]
----
/*
testrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
  // ...
}

loadtestrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
  // ...
}
*/
----

== why?

==== official gradle plugin support

Currently SmartBear is not supporting gradle plugin. At the moment only link:http://smartbearsoftware.com/repository/maven2/com/smartbear/soapui/soapui-maven-plugin/5.3.1-RC/soapui-maven-plugin-5.3.1-RC.pom[SoapUI Maven Plugin] officially supported.

SmartBear provides platform dependant scripts for SoapUI test project execution, but it's not so convenient.
For example, to execute SoapUI tests using testrunner (version: 5.3.0) tool you can use these commands:

==== running tests on windows

[source,cmd]
----
C:\path\to\SoapUI-5.3.0\bin\testrunner.bat C:\path\to\soapui-test-project.xml
----

==== running tests on unix

[source,bash]
----
/path/to/SoapUI-5.3.0.app/Contents/Resources/app/bin/testrunner.sh /path/to/soapui-test-project.xml
----

==== running tests using gradle plugin

but with configured build script you only need to execute this:

[source,bash]
gradle testrunner
gradle loadtestrunner

you can pre-configure once all needed properties / configurations using different tasks for reuse

== what's inside?

This plugin has all functionality you might need ...almost :)

Anyway, it could be easily extend, really...

=== configuration properties

==== base (allowed for testrunner and loadtestrunner tasks)

[width="100%"]
|==============================================================================================================================================================================================================================================================================
| property                  | arg | default                 | description

| failOnError               | N/A | true                    | sets if gradle plugin execution should stop and fails on any plugin configuration errors occurs

| projectFile               | N/A | soapui-test-project.xml | sets the SoapUI project file containing the tests to run
| outputFolder              | -f  | build/soapui            | sets the output folder to export results to

| projectProperties         | -P  |                         | sets list of "key=value" project properties
| globalProperties          | -G  |                         | sets list of "key=value" global properties
| systemProperties          | -D  |                         | sets list of "key=value" system properties

| settingsFile              | -t  |                         | sets the SoapUI settings file
| endpoint                  | -e  |                         | sets the endpoint to use for all test requests
| domain                    | -d  |                         | sets the domain to use for any authentications
| host                      | -h  |                         | sets the host to use by all test-requests, the existing endpoint port and path will be used
| username                  | -u  |                         | sets the username to use for any authentications
| password                  | -p  |                         | sets the password to use for any authentications
| wssPasswordType           | -w  |                         | sets the WSS password-type to use for any authentications. Setting this will result in the addition of WS-Security UsernamePassword tokens to any outgoing request containing the specified username and password
| projectPassword           | -x  |                         | sets SoapUI project password
| soapUISettingsPassword    | -v  |                         | sets SoapUI settings password
| enableUI                  | -i  | false                   | enables Swing UI components

| testSuite                 | -s  |                         | sets the TestSuite to run. If not set all TestSuites in the specified project file are run
| testCase                  | -c  |                         | sets the TestCase to run. If not set all TestCases in the specified project file are run

| printReport               | -r  | true                    | a flag controlling if a summary should be printed
| saveAfterRun              | -S  | false                   | saves the project after running the tests

|==============================================================================================================================================================================================================================================================================

==== testrunner specific

[width="100%"]
|================================================================================================================================
| property                  | arg | default                 | description

| exportAll                 | -a  | true                    | adds console appender results to groovy log
| junitReport               | -j  | true                    | Ñollects TestRun results and creates JUnitReports
| junitReportWithProperties | -J  | true                    | include JUnit XML reports adding test
| ignoreErrors              | -I  | false                   | a flag controlling if errors are ignored
| printAlertSiteReport      | -M  | true                    | creates a Test Run Log Report in XML format

| maxErrors                 | -m  | 5                       | sets the maximum number of TestStep errors to save for each testcase

|================================================================================================================================

==== loadtestrunner specific

[width="100%"]
|=======================================================================================================================================================
| property                  | arg | default                 | description

| loadTest                  | -l  |                         | sets the Load Test to run. If not set all Load Tests in the specified project file are run
| limit                     | -m  |                         | override limit property of Load Test
| threadCount               | -n  |                         | override thread count property of Load Test

|=======================================================================================================================================================

== testrunner configuration customization

using groovy API feel free to do pretty much whatever you need.
link:https://github.com/daggerok/soapui-runner-example/commit/9a8b40311600ed631703e7c0de1effa3e29e805d[For example, to specify exact testSuites for run] you can use next configuration in your gradle build:

==== execute only needed TestSuite list

[source,gradle]
----
apply plugin: io.github.daggerok.SoapUITestRunnerPlugin

task soapUITestSuites(dependsOn: [

  'TestSuite 1',
  'TestSuite 2',

].collect { suiteName ->
  tasks.create(name: suiteName, type: io.github.daggerok.tasks.SoapUITestRunnerTask) {
    testSuite = suiteName
    outputFolder = "$buildDir/soapui/$suiteName"
  }
})
----

note: same approach can be used for testCases.
link:https://github.com/daggerok/soapui-runner-example/commit/84f71229b08934a0598fdef18acd497b8dacb1a1[For example: to execute only needed test cases] your build script might looks like so:

==== execute some concrete TestCases

[source,gradle]
----
apply plugin: io.github.daggerok.soapui-testrunner'

import io.github.daggerok.tasks.SoapUITestRunnerTask

Task[] soapUITasks = [

    'TestCase 1',
    'TestCase 2',
    'TestCase 3',
    'TestCase 4',
    'TestCase 5',

].collect { testCaseName ->

  def noSpaceCase = testCaseName.replaceAll(/\s+$/, '').capitalize()

  tasks.create(name: noSpaceCase, type: SoapUITestRunnerTask) {
    testCase = noSpaceCase
    outputFolder = "$buildDir/soapui/testCases/$noSpaceCase"
    projectProperties = [
        'apiEndpoint=https://jsonplaceholder.typicode.com'
    ]
  }
}

task soapUITestCases(dependsOn: soapUITasks)
----

== plugin info

- Gradle API 4.0.1
- Groovy 2.4.11
- SoapUI 5.3.0

==== current milestone

5.3.1-RC

==== support old versions:

- *5.2:* 5.2.1, 5.2.0
- *5.1:* 5.1.3, 5.1.2
- *5.0:* 5.0.1-hotfix.0 (5.0.0-beta), [line-through]#5.0.1#, 5.0.0-hotfix.1, [line-through]#5.0.0#
- *4.6:* 4.6.4-hotfix.0, [line-through]#4.6.4#, 4.6.3-rc.0, [line-through]#4.6.3#, 4.6.2, 4.6.1

note: strike through version [line-through]#x.y.z# cloud be buggy. You have to use next one instead.

== development and contribution

Feel free to contribute or link:https://github.com/daggerok/soapui-runner/issues[open an issue]

Publish locally for development purpose:

[source,gradle]
bash gradlew clean build install publish

For testing locally published plugin into maven repo publishing use link:https://github.com/daggerok/soapui-runner-example/blob/master/build.gradle[this] example

Don't try publish new version of plugin to gradle portal (it's available only for owner)

[source,gradle]
bash gradlew publishPlugins

== FYI

you can apply string identifier or FQDN class name for each plugin:

[source,groovy]
----
// soapui-loadtestrunner plugin (turns on loadtestrunner task):
apply plugin: io.github.daggerok.SoapUILoadTestRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-loadtestrunner'

// soapui-testrunner plugin (turns on testrunner task):
apply plugin: io.github.daggerok.SoapUITestRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-testrunner'

// soapui-runner plugin (turns on both: testrunner and loadtestrunner tasks):
apply plugin: io.github.daggerok.SoapUIRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-runner'
----

=== issues

==== soapuios

if you faced with errors like

[source,bash]
----
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory
...
----

from 5.2 Release Notes (2015-07-02):

> SoapUI failed to load plugins when you run tests with testrunner.bat and the current directory differed from <SoapUI>\bin

fix: rename $HOME/.soapuios folder to NOT.soapuios

[source,bash]
----
mv -f $HOME/.soapuios $HOME/NOT.soapuios
----

link:https://stackoverflow.com/questions/31409653/classnotfoundexception-after-updating-to-soapui-5-2-0[read more]
