= SoapUI Runner Gradle Plugin ({project-version}) image:https://travis-ci.org/daggerok/soapui-runner.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/soapui-runner"]
Maksim Kostromin <daggerok@gmail.com>
2017-08-13
:toc:
:revnumber: {project-version}
:example-caption!:
ifndef::sourcedir[:sourcedir: ../groovy]
:icons: font
:toc: left
:numbered:
:github_url: https://github.com/daggerok/soapui-runner
:github_project_path: {github_url}/tree/master
:github_fork_badge: https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png

[discrete]
== Introduction

This is a user manual of soapui-runner.
soap-runner it's a gradle plugin written in groovy.
It simplified configuration of SoapUI test projects and provides theirs cross-platform execution
(at the moment supports only testrunner and loadtestrunner, but it could be very easilly extend - feel free to contribute).

== Why?

=== Officially, gradle plugin is not supported

Currently SmartBear is not supporting gradle plugin. At the moment only link:http://smartbearsoftware.com/repository/maven2/com/smartbear/soapui/soapui-maven-plugin/5.3.1-RC/soapui-maven-plugin-5.3.1-RC.pom[SoapUI Maven Plugin] officially supported.

SmartBear provides platform dependant scripts for SoapUI test project execution, but it's not so convenient.
For example, to execute SoapUI tests using testrunner (version: 5.3.0) tool you can use these commands:

.Example, how to execute tests on windows using SoapUI testrunner.bat
[source,cmd]
C:\path\to\SoapUI-5.3.0\bin\testrunner.bat C:\path\to\soapui-test-project.xml

.Example, how to execute testrunner.sh on unix
[source,bash]
/path/to/SoapUI-5.3.0.app/Contents/Resources/app/bin/testrunner.sh /path/to/soapui-test-project.xml

=== Running tests using soapui-runner gradle plugin

Using preconfigured build script you only need to execute a single command:

[source,bash]
gradle testrunner # or:
gradle loadtestrunner

== What's inside?

There are few plugins and tasks you have to get all functionality you might need
...almost :) Currently, in my daily work and for testing API of my projects, I was required to use only testrunner
and loadtestrunner

.Note
[NOTE]
Anyway, All other existing runner in SoapUI could be easily added to soapui-runner plugin, really. Contributors are welcome!

=== Available plugins and tasks

==== Three plugins available on Gradle Portal

. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-testrunner[SoapUI Test Runner Plugin] soapui-testrunner (`io.github.daggerok.soapui-testrunner`)
. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-loadtestrunner[SoapUI Load Test Runner Plugin] soapui-loadtestrunner (`io.github.daggerok.soapui-loadtestrunner`)
. link:https://plugins.gradle.org/plugin/io.github.daggerok.soapui-runner[SoapUI Runner Plugin] soapui-runner (`io.github.daggerok.soapui-runner`) - contains all tasks: testrunner and loadtestrunner

==== Three tasks available right now

. extDir: helpful task for generating ext folder to be copied inside `$SOAPUI_HOME/bin` (see <<extDir>>)
. testrunner: task run SoapUI Test Suites and/or Test Cases (see <<testrunner>>)
. loadtestrunner: task run SoapUI Load Tests (see <<loadtestrunner>>)

== Installation

There are few ways to integrate soapui-runner in your gradle project.
We are recommending you usi that plugin in separate project.
It's better to not include soapui-runner gradle project as subproject of main project is going to be tested to avoid complexity of dependency resolution, but this is not required.

In general, it could be installed just like so:

.Using plugins approach
[source,groovy]
----
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'http://smartbearsoftware.com/repository/maven2/' }
  }
}

plugins {
  id 'io.github.daggerok.soapui-runner' version '5.3.0-4'
}
----

=== Multi-project build

If you are using multi-project build or for some reasons you don't want apply runner-plugin immediately:

.Do not apply plugin in plugins block
[source,groovy]
----
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'http://smartbearsoftware.com/repository/maven2/' }
  }
}

plugins {
  id 'io.github.daggerok.soapui-runner' version '5.3.0-4' apply false
}

subprojects {
  apply plugin: 'io.github.daggerok.soapui-runner'
  // ...
}
----

=== Gradle version less then 3.0

If you are using gradle <= 3.0, then use apply plugin approach only:

.Use apply plugin approach
[source,groovy]
----
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'http://smartbearsoftware.com/repository/maven2/' }
  }
  dependencies {
    classpath 'gradle.plugin.io.github.daggerok:soapui-runner:5.3.0-4'
  }
}

apply plugin: 'io.github.daggerok.soapui-runner'
----

.Important
IMPORTANT: Make sure you have added required smartbear software maven repository
           in your buildscript for correct plugin dependencies resolution.

==== Many ways apply plugins...

You can apply FQDN class name for each plugin instead (see plugins main classes source code for details):

[source,groovy]
----
// turns on extDir and testrunner tasks:
apply plugin: io.github.daggerok.SoapUITestRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-testrunner'

// turns on extDir and loadtestrunner tasks:
apply plugin: io.github.daggerok.SoapUILoadTestRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-loadtestrunner'

// turns on all tasks: extDir, testrunner and loadtestrunner:
apply plugin: io.github.daggerok.SoapUIRunnerPlugin // or:
apply plugin: 'io.github.daggerok.soapui-runner'
----

== Configuration plugins tasks

You can pre-configure once all needed properties / configurations using runner tasks closures

.Configuration example
[source,groovy]
----
testrunner {
  projectFile 'src/test/resources/soapui-test-project.xml'
  outputFolder 'out/tests'
  failOnError true

  projectProperties = [
    'apiBaseUrl=https://api.github.com'
  ]
}

loadtestrunner {
  projectFile = "$projectDir/soapui-load-tests.xml"
  outputFolder = "buildDir/soapui/load"
}
----

Feel free omit all runners configurations if <<runners-properties>> are good enough for you:

[source,groovy]
----
/*
testrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
  // ...
}

loadtestrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
  // ...
}
*/
----

[[testrunner]]
=== Test (suites and cases) runner

Very extendable and configurable SoapUI testrunner task. For details see: <<testrunner-properties>>

.Example of testrunner task configuration
[source,groovy]
testrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
}

.Execution of test runner task
[source,groovy]
gradle testrunner

==== Test runner configuration customization

Using groovy inside gradle build files we can do pretty much whatever we want.

link:https://github.com/daggerok/soapui-runner-example/commit/9a8b40311600ed631703e7c0de1effa3e29e805d[Look, how easy
you can specify exact testSuites for run]

.Example of testrunner task configuration: how to execute only needed TestSuite list
[source,groovy]
----
apply plugin: io.github.daggerok.SoapUITestRunnerPlugin

task soapUITestSuites(dependsOn: [

  'TestSuite 1',
  'TestSuite 2',

].collect { suiteName ->
  tasks.create(name: suiteName, type: io.github.daggerok.tasks.SoapUITestRunnerTask) {
    testSuite = suiteName
    outputFolder = "$buildDir/soapui/$suiteName"
  }
})
----

.Note
NOTE: same approach can be used for testCases.

link:https://github.com/daggerok/soapui-runner-example/commit/84f71229b08934a0598fdef18acd497b8dacb1a1[Look, how to
execute only needed test cases]

.Example of testrunner execution for some concrete TestCases
[source,groovy]
----
apply plugin: io.github.daggerok.soapui-testrunner'

import io.github.daggerok.tasks.SoapUITestRunnerTask

Task[] soapUITasks = [

    'TestCase 1',
    'TestCase 2',
    'TestCase 3',
    'TestCase 4',
    'TestCase 5',

].collect { testCaseName ->

  def noSpaceCase = testCaseName.replaceAll(/\s+$/, '').capitalize()

  tasks.create(name: noSpaceCase, type: SoapUITestRunnerTask) {
    testCase = noSpaceCase
    outputFolder = "$buildDir/soapui/testCases/$noSpaceCase"
    projectProperties = [
        'apiEndpoint=https://jsonplaceholder.typicode.com'
    ]
  }
}

task soapUITestCases(dependsOn: soapUITasks)
----

[[loadtestrunner]]
=== Load Tests runner

Expandable and configurable load test runner task. See <<loadtestrunner-properties>> for more details

.Example of loadtestrunner task configuration
[source,groovy]
loadtestrunner {
  projectFile = 'soapui-test-project.xml'
  outputFolder = 'build/soapui
}

.Load test runner execution
[source,groovy]
gradle loadtestrunner

[[extDir]]
=== Generate directory for external libraries

Sometimes we need use some external packages, like jdbc drivers.
for that purposes we have to add them inside $SOAPUI_HOME/bin/ext directory
to simplify that process, we can generate needed ext folder to copy it later inside SoapUI ext dir

[source,groovy]
----
repositories { jcenter() }
dependencies {
  extDir 'org.postgresql:postgresql:9.4.1212.jre7'
}
----

[source,groovy]
----
gradle extDir
...
cp -Rf build/soapui/ext $SOAPUI_HOME/bin/ext
----

see SoapUI systemProperty: soapui.ext.libraries: `testrunnert -Dsoapui.ext.libraries=...`

=== Adding new and override generic (parent) properties

If you are using gradle multi-project build, you can define base configuration inside parent build:

[source,groovy]
----
// gradle.build:
allprojects {
  testrunner {
    projectProperties = [
        'os=base',
        'url=https://example.com'
    ]
    systemProperties = [
        "soapui.ext.libraries=$buildDir"
    ]
    // ...
  }
}
----

...and later you might need to override it inside some of your children builds:

[source,groovy]
----
// ./modules/windows/gradle.build
testrunner {
  projectProperties = [
      // add new:
      'newPropjectProp=adding',
      // override existing:
      'os=windows',
      'url=https://microsoft.com'
  ]
  systemProperties = [
      // override existing:
      "soapui.ext.libraries=C:/path/to/SoapUI-5.3.0/bin/ext"
  ]
  // ...
}
----

== Appendix

[[runners-properties]]
=== Runners properties

==== Base (allowed for testrunner and loadtestrunner tasks)

[width="100%"]
|==============================================================================================================================================================================================================================================================================
| property                  | arg | default                 | description

| failOnError               | N/A | true                    | sets if gradle plugin execution should stop and fails on any plugin configuration errors occurs

| projectFile               | N/A | soapui-test-project.xml | sets the SoapUI project file containing the tests to run
| outputFolder              | -f  | build/soapui            | sets the output folder to export results to

| projectProperties         | -P  |                         | sets list of "key=value" project properties
| globalProperties          | -G  |                         | sets list of "key=value" global properties
| systemProperties          | -D  |                         | sets list of "key=value" system properties

| settingsFile              | -t  |                         | sets the SoapUI settings file
| endpoint                  | -e  |                         | sets the endpoint to use for all test requests
| domain                    | -d  |                         | sets the domain to use for any authentications
| host                      | -h  |                         | sets the host to use by all test-requests, the existing endpoint port and path will be used
| username                  | -u  |                         | sets the username to use for any authentications
| password                  | -p  |                         | sets the password to use for any authentications
| wssPasswordType           | -w  |                         | sets the WSS password-type to use for any authentications. Setting this will result in the addition of WS-Security UsernamePassword tokens to any outgoing request containing the specified username and password
| projectPassword           | -x  |                         | sets SoapUI project password
| soapUISettingsPassword    | -v  |                         | sets SoapUI settings password
| enableUI                  | -i  | false                   | enables Swing UI components

| testSuite                 | -s  |                         | sets the TestSuite to run. If not set all TestSuites in the specified project file are run
| testCase                  | -c  |                         | sets the TestCase to run. If not set all TestCases in the specified project file are run

| printReport               | -r  | true                    | a flag controlling if a summary should be printed
| saveAfterRun              | -S  | false                   | saves the project after running the tests

|==============================================================================================================================================================================================================================================================================

[[testrunner-properties]]
==== Test runner specific configuration properties

[width="100%"]
|================================================================================================================================
| property                  | arg | default                 | description

| exportAll                 | -a  | true                    | adds console appender results to groovy log
| junitReport               | -j  | true                    | сollects TestRun results and creates JUnitReports
| junitReportWithProperties | -J  | true                    | include JUnit XML reports adding test
| ignoreErrors              | -I  | false                   | a flag controlling if errors are ignored
| printAlertSiteReport      | -M  | true                    | creates a Test Run Log Report in XML format

| maxErrors                 | -m  | 5                       | sets the maximum number of TestStep errors to save for each testcase

|================================================================================================================================

[[loadtestrunner-properties]]
==== Load test runner specific configuration properties

[width="100%"]
|=======================================================================================================================================================
| property                  | arg | default                 | description

| loadTest                  | -l  |                         | sets the Load Test to run. If not set all Load Tests in the specified project file are run
| limit                     | -m  |                         | override limit property of Load Test
| threadCount               | -n  |                         | override thread count property of Load Test

|=======================================================================================================================================================

== Examples

See some usage examples link:https://github.com/daggerok/soapui-testrunner-example[here]

== Frequently asked questions

=== soapuios

If you faced with errors like

[source,bash]
----
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory
...
----

.From 5.2 Release Notes (2015-07-02):
[NOTE]
SoapUI failed to load plugins when you run tests with testrunner.bat and the current directory differed from <SoapUI>\bin

Fix: rename $HOME/.soapuios folder to NOT.soapuios

[source,bash]
----
mv -f $HOME/.soapuios $HOME/NOT.soapuios
----

link:https://stackoverflow.com/questions/31409653/classnotfoundexception-after-updating-to-soapui-5-2-0[Read more]

== Development and contribution

Feel free to contribute or link:https://github.com/daggerok/soapui-runner/issues[open an issue]

* Publish locally for development purpose:

[source,groovy]
bash gradlew clean build install publish

* For testing locally published plugin into maven repo publishing use link:https://github.com/daggerok/soapui-runner-example/blob/master/build.gradle[this] example

* Don't try publish new version of plugin to gradle portal (it's available only for owner)

[source,groovy]
bash gradlew publishPlugins

* Also Don't try publish new version of plugin documentation to GitHub pages (it's available only for owner)

[source,groovy]
bash gradlew gitPublishPush

=== Supported gradle versions

. plugin:
.. *4:* 4.0.2, 4.0.1, 4.0
. client:
.. *4:* 4.0.2, 4.0.1, 4.0
.. *3:* 3.5, 3.4.1, 3.4, 3.3, 3.2, 3.1, 3.0
.. *2 (apply plugin only):* 2.14, 2.13, 2.12, 2.11, 2.10, 2.9, 2.8

==== Latest plugin release version

link:https://github.com/daggerok/soapui-runner/releases/tag/5.3.0[5.3.0 (plugin: 5.3.0-4)]

==== Current plugin milestone version

link:https://github.com/daggerok/soapui-runner/releases/tag/5.3.1-RC[5.3.1-RC (plugin: 5.3.1-RC-4)]

==== Support SoapUI old versions

- *5.2:* 5.2.1, 5.2.0
- *5.1:* 5.1.3, 5.1.2-hotfix.2, 5.1.2
- *5.0:* 5.0.1-hotfix.0 (5.0.0-beta), [line-through]#5.0.1#, 5.0.0
- *4.6:* 4.6.4, 4.6.3, 4.6.2, 4.6.1

.Note
NOTE: Strike through version [line-through]#x.y.z# cloud be buggy. You have to use next one instead.

.Recomendations
NOTE: We are recommend use latest stable release versions - it should be able support old SoapUI test project file format as well.

== License

link:https://github.com/daggerok/soapui-runner/blob/master/LICENSE[MIT]

= Enjoy! :)
