
Feel free to contribute or link:https://github.com/daggerok/soapui-runner/issues[open an issue]

.build and test
[source,groovy]
----
bash gradlew clean build
----

For testing locally published plugin into maven repo publishing use link:https://github.com/daggerok/soapui-runner-example/blob/master/build.gradle[this] example

.publish locally for development purpose
[source,groovy]
----
bash gradlew clean install publish
----

* note: Don't try publish new version of plugin to gradle portal (it's available only for owner)

.publishing plugin
[source,groovy]
----
bash gradlew publishPlugins
----

.publishing documentation
[source,groovy]
----
bash gradlew clean deploy
----

* note: Don't try publish new version of plugin documentation to GitHub pages (it's available only for owner)

=== Supported gradle versions

. plugin:
.. *4:* 4.2.1, 4.2, 4.1, 4.0.2, 4.0.1, 4.0
. client:
.. *4:* 4.2.1, 4.2, 4.1, 4.0.2, 4.0.1, 4.0
.. *3:* 3.5, 3.4.1, 3.4, 3.3, 3.2, 3.1, 3.0
.. *2 (apply plugin only):* 2.14, 2.13, 2.12, 2.11, 2.10, 2.9, 2.8

==== Latest plugin release version

link:https://github.com/daggerok/soapui-runner/releases/tag/5.3.0[5.3.0 (plugin: 5.3.0-5)]

==== Current plugin milestone version

link:https://github.com/daggerok/soapui-runner/releases/tag/5.3.1-RC[5.3.1-RC (plugin: 5.3.1-RC-4)]

==== Support SoapUI old versions

- *5.2:* 5.2.1, 5.2.0
- *5.1:* 5.1.3, 5.1.2-hotfix.2, 5.1.2
- *5.0:* 5.0.1-hotfix.0 (5.0.0-beta), [line-through]#5.0.1#, 5.0.0
- *4.6:* 4.6.4, 4.6.3, 4.6.2, 4.6.1

.Note
NOTE: Strike through version [line-through]#x.y.z# cloud be buggy. You have to use next one instead.

.Recomendations
NOTE: We are recommend use latest stable release versions - it should be able support old SoapUI test project file format as well.
